### ISSUE TITLE
NEAT Analysis runs fail

### ISSUE THREAD

**Issue by fishbaugher** [fishbaugher/WeatherizationAssistantHosting#13]
When you try to run the analysis on a sample audit your get the RTE:

![image](https://cloud.githubusercontent.com/assets/479175/11798780/fa5963be-a29b-11e5-9ff7-d1fb92fb27fb.png)

Which reminds me update the wa.mde with a LINE NUMBERED version so we can get more information from the RTE.

**Comment by fishbaugher** [comment]
I have seen this kind of SQL error before where Access complains about central functions like IIF() missing. Typically that means references are broken.

**Comment by fishbaugher** [comment]
I wonder if this might be cause by a simple failure to install with the WISE installer...  ALL the references would be broken, and none of the support files would be found.

**Comment by peter-at-sagekey** [comment]
Try to neat again. I did not load the file originally.

**Comment by fishbaugher** [comment]
Resove.  The Engine now runs!
