### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by fishbaugher** [fishbaugher/WeatherizationAssistantHosting#3]
Is there a way to have a branded URL/domain such as:

https://weatherization.mywebsite.com

**Comment by peter-at-sagekey** [comment]
yes and the opening page is a html file that can be modified

**Comment by fishbaugher** [comment]
I own the agilemobilesoft.com domain and would prefer to use that one for branding purposes.  However, I will also mark this a Priority 2 since we need to get it working on the sagekey.net domain first.

**Comment by peter-at-sagekey** [comment]
Good morning Mark

I've added some bindings to the sites that we can test out.
agilemobilesoft.com and www.agilemobilesoft.com for the application.
admin.agilemobilesoft.com:8080 for the administration side.

All these need to get set up in your DNS pointing to 45.32.1.89 to try them
out.

I'm going to be releasing/testing a new version of the admin site this
morning. This has one major new feature which is going to take me a bit to
get set up and configured properly. Testing on Friday afternoon showed it
working almost flawlessly the first time, which worries me. lol  (When I
write THAT much code with that many moving pieces and on the first test the
only "bug" was a missing carriage return when writing out a file, it makes
me think I need to test more!)

I'll let you know when it's all in place. Could be a few hours.


Chris Bremmer
SageKey Software
chrisb@sagekey.com
(250) 770-8878 x7207

**Comment by fishbaugher** [comment]
Chris,  I am glad you were able to log on to the Weatherization Assistant Repository issue tracker!

Very cool about the administrator.  I would like to give it a test when you get it posted.

**Comment by fishbaugher** [comment]
YEA!, just added the IP address to my agilemobilesoft.com DNS route and it just worked!  Nice.

![image](https://cloud.githubusercontent.com/assets/479175/14259035/16334fda-fa73-11e5-99d0-9a3fd61def06.png)

**Comment by fishbaugher** [comment]
Looks like this DNS redirect worked.
