### ISSUE TITLE
Error linking waReport

### ISSUE THREAD

**Issue by fishbaugher** [fishbaugher/WeatherizationAssistantHosting#4]
When  linking a new backend or to waReport, the waReport.mdb starts but has trouble with the AutoStart macro call.
![image](https://cloud.githubusercontent.com/assets/479175/11797970/d3938c8e-a294-11e5-99a6-f79d5a6f6f23.png)

**Comment by fishbaugher** [comment]
When you close the window above, you get:
![image](https://cloud.githubusercontent.com/assets/479175/11798008/19518dca-a295-11e5-9851-e6e5e4b30440.png)

**Comment by peter-at-sagekey** [comment]
What library supplies the container for "acxStartdate", "acxprogress"?

**Comment by fishbaugher** [comment]
I think this is an old error.
