### ISSUE TITLE
MDE Distribution

### ISSUE THREAD

**Issue by fishbaugher** [fishbaugher/WeatherizationAssistantHosting#5]
Both the waReport.mdb and waf-master.mdb should be compiled into .mde

1) waReport.mde
2) wa.mde

**Comment by peter-at-sagekey** [comment]
An attempt was made to compile. Had runtime issues with Activex will need work. They were different from the non compiled versions.

**Comment by fishbaugher** [comment]
Probably the best thing would be for me to study the changes to the design master, then do the MDE compiles on my development machine the provide an installer (WISE).  

How does each user get their own installation?  Does each user have a c:\programData folder? 

Does each user get their own registry entries?

ALSO, note that there are quite a number of support files included in the installer.  It would appear that the waf-master.mdb front end was installed to a location missing all the support files.

Did I ever send you an installer?  Perhaps not since the installers typically have the Access 2010 runtime included which should not apply in the Hosting case.

**Comment by fishbaugher** [comment]
I think the basics are working in mdb form and we can distribute MDEs later.
