### ISSUE TITLE
Reduce wasted menu space

### ISSUE THREAD

**Issue by fishbaugher** [fishbaugher/WeatherizationAssistantHosting#7]
Let's see if we can get rid of the excess vertical custom menu space:
<img width="499" alt="screen shot 2015-12-14 at 7 17 52 pm" src="https://cloud.githubusercontent.com/assets/479175/11798306/92a42442-a297-11e5-8335-e37f043adb24.png">

**Comment by peter-at-sagekey** [comment]
agreed

**Comment by fishbaugher** [comment]
Chris,  is there a plan for how to tighten up the wasted vertical space here?  I will do a little research because I am pretty sure this is an Access not a Cloud issue.

**Comment by fishbaugher** [comment]
There is a way.  Just right click in the menu area and select Minimize.  The behavior is what we want, which is a minimized view (hidden).  To reveal the custom Add-Ins for Weatherization, you just have to click the Add-Ins tab which DOES remain in view.  But this method recovers all the vertical space.  Once minimized, any click outside the ribbon makes it disappear.  So, I will call this one closed.
